import { Lista } from "./lista";

export const PlayLista: Lista[] = [
  {
    id:'1',
    album:'Anos 80',
    nome: 'As Mais dos Anos 80',
    audio: [{musica:  '../../../assets/audio/musica5.mpeg ',
            nome:" Musica Boa : ",
            id:'1 : ',
            artista: " Boby Marley :"},
            {musica:  '../../../assets/audio/musica3.mpeg',
            nome:"Musica Boa : ",
            id:'2 : ',artista:"Michel Jakson : "},
            {musica:'../../../assets/audio/musica2.mpeg',
            nome:"Musica Boa : ",
            id:'3 : ',artista:   "   Prince Prince  :"},
            {musica:'../../../assets/audio/musica4.mpeg',
            nome:"Musica Boa : ",
            id:'4 : ',artista:"  Jhon Bom Jovi     : "},
            {musica:'../../../assets/audio/musica1.mpeg',
            nome:"Musica Boa : ",
            id:'5 : ',artista:"  Paulo Mendes:"},
            {musica:'../../../assets/audio/musica2.mpeg',
            nome:"Musica Boa : ",
            id:'6 : ',artista:"Rick  T Martim   "},
            {musica:'../../../assets/audio/musica2.mpeg',
            nome:"Musica Boa : ",
            id:'7 : ',artista:"João Tapioca : "},
  ],
    foto:'../../../assets/images/anos80.jpg'

  },
  
  {
    id:'2',
    album:'Anos 90',
    nome: 'As Mais dos Anos 90',
    audio: [{musica:'../../../assets/audio/musica5.mpeg',
    nome:"Musica Boa : ",
            id:'1 : ',artista:"Jack Jonson"},
            {musica:'../../../assets/audio/musica3.mpeg',
            nome:"Musica Boa : ",
            id:'2 : ',artista:"Madona"},
            {musica:'../../../assets/audio/musica2.mpeg',
            nome:"Musica Boa : ",
            id:'3 : ',artista:"U2"},
            {musica:'../../../assets/audio/musica4.mpeg',
            nome:"Musica Boa : ",
            id:'4 : ',artista:"Irom Maidem"},
            {musica:'../../../assets/audio/musica1.mpeg',
            nome:"Musica Boa : ",
            id:'5 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica2.mpeg',
            nome:"Musica Boa : ",
            id:'6 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica2.mpeg',
            nome:"Musica Boa : ",
            id:'7 : ',artista:"Michel Jakson"},
  ],
    foto:'../../../assets/images/anos90.jpg'

  },
  {
    id:'2',
    album:'Anos 2000',
    nome: 'As Mais dos Anos 2000',
    audio: [{musica:'../../../assets/audio/musica5.mpeg',
    nome:"Musica Boa : ",
            id:'1 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica3.mpeg',
            nome:"Musica Boa : ",
            id:'2 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica2.mpeg',
            nome:"Musica Boa : ",
            id:'3 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica4.mpeg',
            nome:"Musica Boa : ",
            id:'4 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica1.mpeg',
            nome:"Musica Boa : ",
            id:'5 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica2.mpeg',
            nome:"Musica Boa : ",
            id:'6 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica2.mpeg',
            nome:"Musica Boa : ",
            id:'7 : ',artista:"Michel Jakson"},
  ],
    foto:'../../../assets/images/anos2000.jpg'

  },
  {
    id:'4',
    album:'Pop Rock',
    nome: 'As Mais do PopRock',
    audio: [{musica:'../../../assets/audio/musica5.mpeg',
    nome:"Musica Boa : ",
            id:'1 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica3.mpeg',
            nome:"Musica Boa : ",
            id:'2 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica2.mpeg',
            nome:"Musica Boa : ",
            id:'3 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica4.mpeg',
            nome:"Musica Boa : ",
            id:'4 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica1.mpeg',
            nome:"Musica Boa : ",
            id:'5 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica2.mpeg',
            nome:"Musica Boa : ",
            id:'6 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica2.mpeg',
            nome:"Musica Boa : ",
            id:'7 : ',artista:"Michel Jakson"},
  ],
    foto:'../../../assets/images/poprock.jpg'

  },

  {
    id:'5',
    album:'Rock Brasil',
    nome: 'Rock Brasil',
    audio: [{musica:'../../../assets/audio/musica5.mpeg',
    nome:"Musica Boa : ",
            id:'1 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica3.mpeg',
            nome:"Musica Boa : ",
            id:'2 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica2.mpeg',
            nome:"Musica Boa : ",
            id:'3 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica4.mpeg',
            nome:"Musica Boa : ",
            id:'4 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica1.mpeg',
            nome:"Musica Boa : ",
            id:'5 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica2.mpeg',
            nome:"Musica Boa : ",
            id:'6 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica2.mpeg',
            nome:"Musica Boa : ",
            id:'7 : ',artista:"Michel Jakson"},
  ],
    foto:'../../../assets/images/rockbrasil.jpg'

  },
  {
    id:'6',
    album:'Rock Internacional',
    nome: 'Rock Internacional',
    audio: [{musica:'../../../assets/audio/musica5.mpeg',
    nome:"Musica Boa : ",
            id:'1 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica3.mpeg',
            nome:"Musica Boa : ",
            id:'2 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica2.mpeg',
            nome:"Musica Boa : ",
            id:'3 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica4.mpeg',
            nome:"Musica Boa : ",
            id:'4 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica1.mpeg',
            nome:"Musica Boa : ",
            id:'5 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica2.mpeg',
            nome:"Musica Boa : ",
            id:'6 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica2.mpeg',
            nome:"Musica Boa : ",
            id:'7 : ',artista:"Michel Jakson"},
  ],
    foto:'../../../assets/images/rockinternacional.jpg'

  },
  {
    id:'7',
    album:'Sertanejo',
    nome: 'O Melhor do Sertanejo',
    audio: [{musica:'../../../assets/audio/musica5.mpeg',
    nome:"Musica Boa : ",
            id:'1 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica3.mpeg',
            nome:"Musica Boa : ",
            id:'2 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica2.mpeg',
            nome:"Musica Boa : ",
            id:'3 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica4.mpeg',
            nome:"Musica Boa : ",
            id:'4 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica1.mpeg',
            nome:"Musica Boa : ",
            id:'5 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica2.mpeg',
            nome:"Musica Boa : ",
            id:'6 : ',artista:"Michel Jakson"},
            {musica:'../../../assets/audio/musica2.mpeg',
            nome:"Musica Boa : ",
            id:'7 : ',artista:"Michel Jakson"},
  ],
    foto:'../../../assets/images/sertanejo.jpg'

  },
  {
    id:'8',
    album:'Forro',
    nome: 'Forro das Antigas',
    audio: [{musica:'../../../assets/audio/musica5.mpeg',
    nome:"Musica Boa : ",
    id:'1 : ',artista:"Michel Jakson"},
    {musica:'../../../assets/audio/musica3.mpeg',
    nome:"Musica Boa : ",
    id:'2 : ',artista:"Michel Jakson"},
    {musica:'../../../assets/audio/musica2.mpeg',
    nome:"Musica Boa : ",
    id:'3 : ',artista:"Michel Jakson"},
    {musica:'../../../assets/audio/musica4.mpeg',
    nome:"Musica Boa : ",
    id:'4 : ',artista:"Michel Jakson"},
    {musica:'../../../assets/audio/musica1.mpeg',
    nome:"Musica Boa : ",
    id:'5 : ',artista:"Michel Jakson"},
    {musica:'../../../assets/audio/musica2.mpeg',
    nome:"Musica Boa : ",
    id:'6 : ',artista:"Michel Jakson"},
    {musica:'../../../assets/audio/musica2.mpeg',
    nome:"Musica Boa : ",
    id:'7 : ',artista:"Michel Jakson"},
],
    foto:'../../../assets/images/forro.jpg'

  },
];



